### ISSUE TITLE
add modern tooltips

### ISSUE THREAD

**Issue by KyleMit** [VermontDepartmentOfHealth/docs#23]
Especially for `<abbr title="Vermont Department of Health">VDH</abbr>` elements with `title` attribute.

Here are  but biggest driver is going to be perf/bundle size.  We don't need a lot of features

* [21 best open-source tooltip plugins made with CSS, jQuery, and JavaScript](https://www.appcues.com/blog/73-tooltip-plugins-made-with-jquery-css-javascript-or-more)
* [28 CSS Tooltips](https://freefrontend.com/css-tooltips/)
* [Plain Javascript Tooltip](https://stackoverflow.com/q/18359193/1366033)
* [Add a tooltip to a div](https://stackoverflow.com/q/7117073/1366033)

# CSS

### [microtip](https://github.com/ghosh/microtip#installation) - [1.2 KB](https://unpkg.com/microtip@0.2.2/microtip.min.css)

```html
<button aria-label="Hey tooltip!" data-microtip-position="up" role="tooltip">
```

### [wenk](https://github.com/tiaanduplessis/wenk) - [0.7 KB](https://unpkg.com/wenk@1.0.8/dist/wenk.min.css)

```html
<span data-wenk="I'm to the right!" data-wenk-pos="right">Wenk to the right!</span>
```

### [W3 Schools](https://www.w3schools.com/css/css_tooltip.asp) - [0.3 KB](https://rawcdn.githack.com/KyleMit/libraries/a4b2c1f53184b7e11331257217342d80738246ce/libraries/tooltips.css)

```html
<div class="tooltip">Hover over me
  <span class="tooltiptext">Tooltip text</span>
</div>
```

### [Custom](https://jsfiddle.net/KyleMit/qodrw1ys/)

```html
<abbr data-tooltip="Vermont Department of Health">VDH</abbr> / 
```

```css
*[data-tooltip] {
  position: relative;
}

*[data-tooltip]::after {
  content: attr(data-tooltip);

  position: absolute;
  bottom: -145%;
  left: -100%;
  display: inline-block;
  white-space: pre;
  z-index: 99;
  padding: 2px 7px;
  font-size: 1rem;
  line-height: 1rem;
  color: white;
  background: black;
  box-shadow: 1px 1px 1px grey;
  border-radius: 3px;
  pointer-events: none;
  opacity: 0;
  transition: opacity 0.4s ease;
  transition-delay: 0.2s;
}

*[data-tooltip]:hover::after {
  opacity: 1;
}
```

# JS

### [popper.js / tooltip.js](https://github.com/FezVrasta/popper.js) - [7.3 KB](https://unpkg.com/popper.js@1.15.0/dist/umd/popper.min.js) + [2.2. KB](https://unpkg.com/tooltip.js@1.3.2/dist/umd/tooltip.min.js)

```html
<button id="myButton">My Button</button>
```

```js
var el = document.getElementByID("myButton")
new Tooltip(el , {
    placement: 'top', // or bottom, left, right, and variations
    title: "Tooltip text"
});
```
### [Tippy.js](https://github.com/atomiks/tippyjs) - 7.3 KB + [7.6 KB](https://unpkg.com/tippy.js@4.3.5/umd/index.all.min.js)

```html
<button id="myButton">My Button</button>
```

```js
tippy('#myButton', {content: "I'm a Tippy tooltip!"})
```

### [Custom](https://jsfiddle.net/KyleMit/m6h5tqaw/)

```html
<abbr title="Vermont Department of Health">VDH</abbr> / 
```

```js
document.querySelectorAll("body [title]").forEach(function(el) {
  var tooltip = document.createElement("div")
  tooltip.classList.add("tooltip-text")
  tooltip.innerText = el.title

  el.title = ""
  el.classList.add("tooltip")
  el.append(tooltip)

  el.onmouseover = function() { 
    tooltip.classList.add("active"); 
    setTimeout(function() {tooltip.classList.remove("active")  }, 5000)
  }
  el.onmouseout = function() {
    tooltip.classList.remove("active")
  }
});
```
