### ISSUE TITLE
Fix awkward line wrapping of anchor tags

### ISSUE THREAD

**Issue by KyleMit** [VermontDepartmentOfHealth/docs#31]
[Hacknoon](https://hackernoon.com/markdown-code-blocks-and-beyond-lightweight-diagramming-with-plantuml-9c8f2009cac0) seems to handle this pretty well

```css
.content a {
    color: #111;
    padding: 0;
    text-decoration: none;
    background-image: linear-gradient( transparent 0%, transparent calc(50% - 8px), rgba(0, 255, 0, 0.35) calc(50% - 8px), rgba(0, 255, 0, 0.35) 100% );
    transition: background-position 120ms ease-in-out, padding 120ms ease-in-out;
    background-size: 100% 200%;
    background-position: 0 0;
}
.content a:hover {
    padding: 2px 0 4px 0;
    background-image: linear-gradient( transparent 0%, transparent calc(50% - 8px), rgba(0, 255, 0, 1) calc(50% - 8px), rgba(0, 255, 0, 1) 100% );
    background-position: 0 100%;
}
```
